language: java
sudo: required
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - sudo mv settings.xml /usr/local/maven-3.6.3/settings.xml
script:
  - mvn clean compile jib:build