management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:h2:file:~/h2/plc;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    platform: h2
    driverClassName: org.h2.Driver
    initialization-mode: EMBEDDED
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true


logging:
  path: log/
  level:
    io.swagger: DEBUG
