spring:
  http-pool:
    # 连接池最大连接数
    max-total: 3000
    # 每个rount请求的最大连接数
    default-max-per-route: 20
    # 空闲多长时间（毫秒）来校验连接的有效性
    validate-after-inactivity: 2000
    # 建立连接的最大超时时间（毫秒）
    connect-timeout: 20000
    # 获取连接的最大超时时间（毫秒）
    connection-request-timeout: 20000
    # 与服务端保持连接的最大时间（毫秒）
    socket-timeout: 20000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: chester
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
    template:
      retry:
        enabled: true
  redis:
    host: redis
    password: chester@123456
  data:
    mongodb:
      uri: mongodb://root:123456@mongodb:27017/chester?authSource=admin

logging:
  path: log/
  level:
    io.swagger: DEBUG
chester:
  menus:
    - {menuId: 'sys-root', path: '/sys', name: '系统管理',icon: 'mdi-home-account',url: '/sys',sort: 10,type: 'drawer',roles: ['admin'],modify: false}
    - {menuId: 'sys-user', path: '/sys/users', name: '用户管理',icon: 'mdi-home-account',url: '/sys/users',sort: 1,type: 'drawer',roles: ['admin'],modify: false,parentIds: ['sys-root']}
    - {menuId: 'sys-menu', path: '/sys/menus', name: '菜单管理',icon: 'mdi-menu',url: '/sys/menus',sort: 2,type: 'drawer',roles: ['admin'],modify: false,parentIds: ['sys-root']}
    - {menuId: 'sys-role', path: '/sys/roles', name: '角色管理',icon: 'mdi-file-account-outline',url: '/sys/roles',sort: 3,type: 'drawer',roles: ['admin'],modify: false,parentIds: ['sys-root']}
    - {menuId: 'plc-root-data', path: '/plc/data', name: '主数据管理',icon: 'mdi-alpha-r-circle-outline',url: '/plc/data',sort: 1,type: 'drawer',roles: ['admin','operator']}
    - {menuId: 'plc-machine', path: '/plc/machines', name: '设备管理',icon: 'mdi-apache-kafka',url: '/data/machines',sort: 1,type: 'drawer',roles: ['admin','operator'],parentIds: ['plc-root-data']}
    - {menuId: 'plc-material', path: '/plc/materials', name: '物料维护',icon: 'mdi-database-refresh',url: '/data/materials',sort: 3,type: 'drawer',roles: ['admin','operator'],parentIds: ['plc-root-data']}
    - {menuId: 'plc-root-task', path: '/plc/task', name: '生产管理',icon: 'mdi-alpha-r-circle-outline',url: '/plc/task',sort: 1,type: 'drawer',roles: ['admin','operator']}
    - {menuId: 'plc-mission', path: '/plc/missions', name: '任务管理',icon: 'mdi-screw-machine-flat-top',url: '/task/missions',sort: 2,type: 'drawer',roles: ['admin','operator'],parentIds: ['plc-root-task']}
    - {menuId: 'plc-job', path: '/plc/jobs', name: '排程管理',icon: 'mdi-database-refresh',url: '/task/jobs',sort: 4,type: 'drawer',roles: ['admin','operator'],parentIds: ['plc-root-task']}
printUrl: http://localhost:9999